import type { Reference } from "@/types";

export const references: Reference[] = [
  {
    slug: "armatis-supply-chain",
    client: "Armatis",
    category: ["IA & Intelligence Artificielle"],
    description: {
      fr: "Optimisation IA de la Supply Chain pour Armatis — +24% de productivité logistique globale.",
      en: "AI-driven supply chain optimization for Armatis — +24% overall logistics productivity.",
    },
    year: 2024,
    imageSrc: "/images/references/inpi.webp",
    logoSrc: "/images/logos/armatis.png",
  },
  {
    slug: "armatis-qualite",
    client: "Armatis",
    category: ["IA & Intelligence Artificielle"],
    description: {
      fr: "Application métier augmentée de suivi de qualité pour Armatis.",
      en: "AI-augmented quality tracking business application for Armatis.",
    },
    year: 2024,
    imageSrc: "/images/references/collabs.png",
    logoSrc: "/images/logos/armatis.png",
  },
  {
    slug: "armatis-ia",
    client: "Armatis",
    category: ["IA & Intelligence Artificielle"],
    description: {
      fr: "Optimisation IA des processus internes Armatis.",
      en: "AI optimisation of Armatis internal processes.",
    },
    year: 2024,
    imageSrc: "/images/references/laposte.jpg",
    logoSrc: "/images/logos/armatis.png",
  },
  {
    slug: "armatis-public",
    client: "Armatis",
    category: ["IA & Intelligence Artificielle"],
    description: {
      fr: "Projet de transformation IA pour le secteur public avec Armatis.",
      en: "AI transformation project for the public sector with Armatis.",
    },
    year: 2024,
    imageSrc: "/images/references/france-competences.jpg",
    logoSrc: "/images/logos/armatis.png",
  },
  {
    slug: "inpi-portail-open-data",
    client: "INPI",
    category: ["Développement"],
    description: {
      fr: "Création et TMA du Portail Open Data de l'INPI — données Dessins & Modèles, Brevets, Entreprises.",
      en: "Development and ongoing maintenance of INPI's Open Data Portal — Designs, Patents, and Companies datasets.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/Capture_d_ecran_2023_12_01_a_17_51_49_c6caa09d6e.png",
    logoSrc: undefined,
  },
  {
    slug: "laposte-veiller-sur-mes-parents",
    client: "La Poste",
    category: ["Conseil & Design", "Développement"],
    description: {
      fr: "Création et TMA de l'application mobile \"Veiller sur mes Parents\" pour La Poste.",
      en: "Creation and maintenance of La Poste's \"Veiller sur mes Parents\" mobile app.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/unnamed_8d06d23b57.png",
    logoSrc: undefined,
  },
  {
    slug: "fdj-centre-service-applicatif",
    client: "FDJ",
    category: ["Conseil & Design", "Développement"],
    description: {
      fr: "Centre de service applicatif FDJ — équipe AGILE pluridisciplinaire dédiée.",
      en: "FDJ application service centre — dedicated multidisciplinary Agile team.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/Capture_d_ecran_2023_12_01_a_13_39_25_0aa82a5acc.png",
    logoSrc: undefined,
  },
  {
    slug: "cmn-hebergement-infogerance",
    client: "Centre des Monuments Nationaux",
    category: ["Cloud"],
    description: {
      fr: "Hébergement et infogérance de la plateforme des 100 sites web et du portail du CMN.",
      en: "Hosting and managed services for the CMN's platform of 100 websites and main portal.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/5bae9414da71_carte_passion_monuments_fond_transparent_fbd5c8e0df.png",
    logoSrc: undefined,
  },
  {
    slug: "pold-portail-innovation",
    client: "POLD",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Création, TMA et infogérance du portail POLD — Le Catalyseur de l'innovation.",
      en: "Creation, maintenance, and hosting of POLD's innovation hub portal.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/keys_c17f19a606.webp",
    logoSrc: undefined,
  },
  {
    slug: "maif-objectif-brevet",
    client: "MAIF & Rue des écoles",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Création de l'application \"Objectif Brevet\" à destination des élèves de 3ème, en partenariat avec la MAIF.",
      en: "Development of the \"Objectif Brevet\" revision app for Year 10 students, in partnership with MAIF.",
    },
    year: 2025,
    imageSrc: "https://www.steamulo.com/uploads/Capture_d_ecran_2025_05_09_a_15_24_54_b6cbb67f42.png",
    logoSrc: undefined,
  },
  {
    slug: "asc-refonte-portail",
    client: "Agence du Service Civique",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Refonte, TMA et hébergement du portail de l'Agence du Service Civique.",
      en: "Redesign, maintenance, and hosting of the Service Civique Agency portal.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/screenshot_asc_f0b0000283.png",
    logoSrc: undefined,
  },
  {
    slug: "marketpay-plateforme-relation-client",
    client: "Market Pay",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Création, TMA et hébergement de la plateforme de digitalisation de la relation client Market Pay.",
      en: "Creation, maintenance, and hosting of Market Pay's customer relationship digitalisation platform.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/laptop_fly_noshadow_min_5b5c84461c.png",
    logoSrc: undefined,
  },
  {
    slug: "carrefour-location-liberte",
    client: "Carrefour",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "MVP de l'application mobile Location Liberté pour Carrefour.",
      en: "MVP of the Location Liberté mobile app for Carrefour.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/Capture_d_ecran_2023_12_26_a_17_22_57_bf39e4a469.png",
    logoSrc: undefined,
  },
  {
    slug: "carrefour-portail-energies",
    client: "Carrefour",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Création du portail Carrefour Energies.",
      en: "Creation of the Carrefour Energies portal.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/th_a7b63cdd60.jpg",
    logoSrc: undefined,
  },
  {
    slug: "ush-portail-principal",
    client: "Union Sociale pour l'Habitat",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Refonte, TMA et infogérance du portail USH avec extranet dédié aux professionnels de l'immobilier.",
      en: "Redesign, maintenance, and managed services for the USH portal with a dedicated extranet for real estate professionals.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/logo_vignette_185a6ea022.jpg",
    logoSrc: undefined,
  },
  {
    slug: "france-competences-tma-si",
    client: "France compétences",
    category: ["Conseil & Design", "Développement"],
    description: {
      fr: "Accord cadre TMA applicative SI pour France compétences — Certif Pro, CEP, Sites web.",
      en: "Framework agreement for application SI maintenance for France compétences — Certif Pro, CEP, websites.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/dossier_1600x700_adafde89ea.jpg",
    logoSrc: undefined,
  },
  {
    slug: "bpce-mon-expert",
    client: "BPCE",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Création et TMA de Mon Expert, outil de gestion des leads en agence pour BPCE.",
      en: "Creation and maintenance of Mon Expert, a lead management tool for BPCE agency branches.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/14_8bbcd5e9c3.png",
    logoSrc: undefined,
  },
  {
    slug: "laposte-si-crc",
    client: "La Poste",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Reprise TMA, infogérance et hébergement du SI CRC TA & FACTU pour La Poste.",
      en: "Takeover, maintenance, and hosting of La Poste's CRC TA & FACTU information system.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/Capture_d_ecran_2023_12_04_a_12_13_33_dbda1f49f6.png",
    logoSrc: undefined,
  },
  {
    slug: "louvre-hotels-machine-learning",
    client: "Louvre Hotels",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Usage du Machine Learning pour l'analyse prédictive chez Louvre Hotels.",
      en: "Machine Learning implementation for predictive analytics at Louvre Hotels.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/LHG_Home_groupe_desktop_b1365b05b2.jpg",
    logoSrc: undefined,
  },
  {
    slug: "ush-bienveo",
    client: "Union Sociale pour l'Habitat",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Refonte et TMA du portail Bienveo — logements HLM disponibles à la location ou à la vente.",
      en: "Redesign and maintenance of the Bienveo portal for available social housing rentals and sales.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/visuel_bienveo_1024x711_6260947a8a.jpg",
    logoSrc: undefined,
  },
  {
    slug: "asc-audit-ux",
    client: "Agence du Service Civique",
    category: ["Conseil & Design"],
    description: {
      fr: "Audit UX du parcours de candidature pour l'Agence du Service Civique.",
      en: "UX audit of the application journey for the Service Civique Agency.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/audit_ux_asc_4_d65224ddca.png",
    logoSrc: undefined,
  },
  {
    slug: "sncf-guidage-malvoyants",
    client: "SNCF",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Prototype d'application de guidage des malvoyants pour SNCF.",
      en: "Prototype navigation app for visually impaired passengers for SNCF.",
    },
    year: 2024,
    imageSrc: "https://www.steamulo.com/uploads/Capture_d_ecran_2024_01_30_a_09_53_40_bacd4b782d.png",
    logoSrc: undefined,
  },
  {
    slug: "ush-orfi",
    client: "Union Sociale pour l'Habitat",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Création et TMA d'ORFI, application mobile de recueil des faits d'incivilités pour l'USH.",
      en: "Creation and maintenance of ORFI, a mobile app for reporting anti-social behaviour for USH.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/orfi_f7ef59c2ef.jpeg",
    logoSrc: undefined,
  },
  {
    slug: "residences-yvelines-essonne-portail",
    client: "Les Résidences Yvelines Essonne",
    category: ["Conseil & Design", "Développement", "Cloud"],
    description: {
      fr: "Refonte et TMA du portail Les Résidences Yvelines Essonne.",
      en: "Redesign and maintenance of the Les Résidences Yvelines Essonne portal.",
    },
    year: 2023,
    imageSrc: "https://www.steamulo.com/uploads/Capture_d_ecran_2023_12_03_a_18_37_43_dd3896f207.png",
    logoSrc: undefined,
  },
];
